---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: app-with-postgres
  namespace: someteamname
spec:
  image: ghcr.io/nais/testapp:latest
  postgres:
    clusterName: foobar
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: app-without-postgres
  namespace: someteamname
spec:
  image: ghcr.io/nais/testapp:latest
